### ISSUE TITLE
Use the Uppsala OSGi bundles

### ISSUE THREAD

**Issue by egonw** [RBVI/chemViz2#1]
...  and ensure Uppsala is building Java6 versions of them.

http://pele.farmbio.uu.se/bioclipse/cdk/1.5.x/

**Comment by RBVI** [comment]
Need to provide more flexibility for labels.  If the image label attribute is a list, and there are multiple compounds per node, use the label that matches the index for the compound.

**Comment by egonw** [comment]
With the 1.5.13 version here: http://pele.farmbio.uu.se/bioclipse/cdk/cdk-1.5.13/

**Comment by egonw** [comment]
No longer relevant.
